<?php
/**
 * Implements hook_theme().
 */
function admin_enquires_theme($existing, $type, $theme, $path) {
    return [
        'admin_enquires' => [
            'render element' => 'element',
            'template' => 'admin-enquires',
            'variables' => [
                'name' => '',
                'email' => '',
                'phone' => '',
                'inquiry' => '',
                'hotel' => '',
            ],
        ],
    ];
}
