<?php
/**
 * Implements hook_theme().
 */
function admin_enquires_theme($existing, $type, $theme, $path) {
  return [
    'admin_enquires' => [
      'render element' => 'element',
      'template' => 'admin-enquires',
      'variables' => [
        'name' => '',
        'email' => '',
        'phone' => '',
        'inquiry' => '',
        'hotel' => '',
      ],
    ],
  ];
}


/**
 * Implements hook_permission()
 */
function admin_enquires_permission() {
  return array(
    'use admin enquires' => array(
      'title' => t('Use the admin enquires'),
    ),
  );
}